### ISSUE TITLE
Deprecation warning no_tab_linter / und mehr Linter-Probleme

### ISSUE THREAD

**Issue by miraKlein** [INWT/INWTUtils#15]
```
Linter no_tab_linter was deprecated in lintr version 3.1.0. Use whitespace_linter instead.
```

Edit - Todos:

- [ ] no_tab_linter (becomes whitespace_linter instead) #17
- [ ] args_no_default_first_linter (becomes function_argument_linter from lintr!) #17
- [ ] double_space_linter #17
- [ ] internal_function_linter (becomes undesirable_operator_linter from lintr?)
- [ ] setwd_linter (selfmade)
- [ ] source_linter (selfmade)
- [ ] options_linter (selfmade)
- [ ] sapply_linter (selfmade)
- [ ] trailing_whitespaces_linter (trailing_whitespaces_linter from lintr?)

**Comment by miraKlein** [comment]
Bei der Gelegenheit habe ich leider festgestellt, dass einige Tests nicht mehr durchlaufen. Wahrscheinlich hat sich das lintr-Paket wieder geändert.

**Comment by miraKlein** [comment]
Sieht aus, als würde die bisher verwendete Logik in den selbst geschriebenen Lintern nicht mehr funktionieren: direkt in ` `source_file$file_lines` nach den unerwünschten Pattern suchen. Stattdessen muss man jetzt mit XML herumhantieren. Das lässt sich auf die Schnelle nicht lösen.

**Comment by miraKlein** [comment]
Die eigenen Linter sind nicht mehr so geschrieben, wie sie heute geschrieben sein müssten. Eine Anleitung findet sich hier: https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html
Die Funktionen in R/03_additionalLinters müssen angepasst werden.
Vorschlag: Einen neuen Branch als "Sammelbranch" abzweigen, und von dort für jeden Einzelschritt (jede reparierte Funktion) einen Branch abzweigen und wieder rein mergen. Erst, wenn alles gelöst ist und der Sammelbranch fehlerfrei läuft, wird er in den master gemerged.
